install docker for circle ci in config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -6,6 +6,15 @@ jobs:
     steps:
       - checkout
       - run:
+          name: Check Docker
+          command: docker --version || echo "Docker not found"
+      - run:
+          name: Install Docker client
+          command: |
+            if ! command -v docker &> /dev/null; then
+              curl -fsSL https://get.docker.com | sh
+            fi
+      - run:
           name: Run project
           command: |
             docker run -d -p 5000:5000 kt2505/my-node-image:latest npm start
